PROGRAM=picoc
SOURCES=\
clibrary.c \
cstdlib/ctype.c \
cstdlib/dirent.c \
cstdlib/errno.c \
cstdlib/math.c \
cstdlib/stdbool.c \
cstdlib/stdio.c \
cstdlib/stdlib.c \
cstdlib/string.c \
cstdlib/time.c \
cstdlib/unistd.c \
debug.c \
expression.c \
heap.c \
include.c \
lex.c \
parse.c \
picoc.c \
platform.c \
platform/library_unix.c \
platform/platform_unix.c \
table.c \
type.c \
variable.c 

CFLAGS+= -I.. -I../.. -I../../../
include ../../common.mak
include ../program.mak
