#define ELF_LOADER_VER_MAJOR 0
#define ELF_LOADER_VER_MINOR 0
#define ELF_LOADER_VER_PATCH 0

//#define CONFIG_ELF_LOADER_SET_MMU        1
#define CONFIG_ELF_LOADER_LIBC_SYMBOLS   1
#define CONFIG_ELF_LOADER_ESPIDF_SYMBOLS 1
#define CONFIG_ELF_LOADER_LOAD_PSRAM     1
#define CONFIG_ELF_LOADER_CACHE_OFFSET   1
#define CONFIG_ELF_LOADER_CUSTOMER_SYMBOLS 1
